config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('', include('to_do.urls')),
    path('user/', include('todo_auth.urls')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('ru/', include(('to_do.urls', 'to_do'), namespace='to_do')),
)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

to_do/urls.py
from django.urls import path
from .views import todo_list_view, todo_create_view, todo_delete_view, todo_detail_view, \
    change_active_view, todo_edit_view, form_view, fake_view

app_name = "todo"

# {% url 'todo:list' %}

urlpatterns = [
    path('', todo_list_view, name='list'),
    path('create/', todo_create_view, name='create'),
    path('delete/<int:id>/', todo_delete_view, name='delete'),
    path('detail/<int:id>/', todo_detail_view, name="detail"),
    path('change/<int:id>/', change_active_view, name='change'),
    path('edit/<int:id>/', todo_edit_view, name='edit'),
    path('form/', form_view, name='fakeform'),
    path('fake/', fake_view, name='fake')
]

templates/layouts/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-icons/font/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    {% block extra_css %}
    {% endblock %}
</head>
<body>

    {% include 'layouts/navbar.html' %}

    <div class="container">
        <div class="row">
                {% block content %}
                {% endblock %}
        </div>
    </div>

    {% block footer %}

    {% endblock %}

    <script src="{% static 'bootstrap/js/bootstrap.bundle.js' %}"></script>
    {% block extra_js %}
    {% endblock %}
</body>
</html>

templates/layouts/navbar.html
{% load static %}
{% load i18n %}

<nav class="navbar navbar-expand-lg bg-dark mb-3" data-bs-theme="dark">
  <div class="container">
    <a class="navbar-brand" href="#">
      <i class="bi bi-pencil-fill"></i>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          {% url 'list' as list %}
          <a class="nav-link 
            {% if request.path == list %}
             active  
            {% endif %} 
          " aria-current="page" href="{% url 'todo:list' %}">{% trans "Home" %}</a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item">
          {% url 'create' as create %}
          <a class="nav-link
          {% if request.path == create %}
            active
          {% endif %}
          " href="{% url 'todo:create' %}">{% trans "Todo create" %}</a>
        </li>
        <li class="nav-item">
          {% url 'logout' as logout %}
          <a class="nav-link 
            {% if request.path == logout %}
             active  
            {% endif %} 
          " aria-current="page" href="{% url 'logout' %}">Logout</a>
        </li>
        
        {% else %}
        <li class="nav-item">
          {% url 'login' as login %}
          <a class="nav-link 
            {% if request.path == login %}
             active  
            {% endif %} 
          " aria-current="page" href="{% url 'login' %}">{% trans "Login" %}</a>
        </li>
        <li class="nav-item">
          {% url 'registration' as registration %}
          <a class="nav-link 
              {% if request.path == registration %}
               active  
              {% endif %} 
            " aria-current="page" href="{% url 'registration' %}">{% trans "Registration" %}</a>
        </li>
        {% endif %}


      </ul>
      {% if request.user.is_authenticated %}
        <form class="d-flex" role="search" method="get">
          <input class="form-control me-2" name="q" type="search" placeholder="{% trans "Search" %}" value="{{ q }}" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">{% trans "Search" %}</button>
        </form>
      {% endif %}
    </div>
  </div>
</nav>